server:
  port: 8001
  servlet:
    context-path: /

spring:
  application:
    name: resilience4j-study
  profiles:
    active: 'dev'

  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    serialization:
      fail-on-empty-beans: false
      order-map-entries-by-keys: true
    deserialization:
      fail-on-unknown-properties: false

management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
